---
title: "Weight of Fish"
author: "Yessica Garay"
date: "`r Sys.Date()`"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```

## read in fishy data
```{r}
fishA11 = read_csv('Fish.csv')
```



# Predicting Fish Weight


## Perch==

```{r}
perchFish = filter(fishA11, Species=='Perch') 
perchModel = lm(Weight~Length1+Length2+Length3+Height+Width, data= perchFish)
summary.lm(perchModel)

```


```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ Length1 + Length2 + Length3 + Height + Width,
               data = perchFish,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")


```


```{r}
summary.out$which[3,]
```

```{r}
#best model
perchBest2=lm(Weight~Height+Width,
data=perchFish)
summary.lm(perchBest2)
```


### Best Models
We find the best models for all three species

### Best Two regressor model





## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements